"""Направления для приёма."""

DIRECTIONS = [
    {
        "faculty_name": "Университет",
        "direction_code": "ПИ",
        "direction_name": "Программная инженерия",
        "budget_places": 12,
        "paid_places": 12,
        "subjects": ["Математика", "Информатика", "Русский язык"],
    },
    {
        "faculty_name": "Университет",
        "direction_code": "ИИ",
        "direction_name": "Искусственный интеллект",
        "budget_places": 15,
        "paid_places": 16,
        "subjects": ["Математика", "Информатика", "Русский язык"],
    },
    {
        "faculty_name": "Университет",
        "direction_code": "БА",
        "direction_name": "Бизнес-аналитика",
        "budget_places": 8,
        "paid_places": 10,
        "subjects": ["Математика", "Обществознание", "Русский язык"],
    },
    {
        "faculty_name": "Университет",
        "direction_code": "ПМ",
        "direction_name": "Прикладная математика",
        "budget_places": 10,
        "paid_places": 12,
        "subjects": ["Математика", "Физика", "Русский язык"],
    },
    {
        "faculty_name": "Университет",
        "direction_code": "ИБ",
        "direction_name": "Информационная безопасность",
        "budget_places": 13,
        "paid_places": 14,
        "subjects": ["Математика", "Информатика", "Русский язык"],
    },
    {
        "faculty_name": "Университет",
        "direction_code": "ВЕБ",
        "direction_name": "Web-разработка",
        "budget_places": 9,
        "paid_places": 10,
        "subjects": ["Математика", "Информатика", "Русский язык"],
    },
    {
        "faculty_name": "Университет",
        "direction_code": "СА",
        "direction_name": "Системное администрирование",
        "budget_places": 7,
        "paid_places": 9,
        "subjects": ["Математика", "Информатика", "Русский язык"],
    },
    {
        "faculty_name": "Университет",
        "direction_code": "РОБ",
        "direction_name": "Робототехника",
        "budget_places": 6,
        "paid_places": 8,
        "subjects": ["Математика", "Физика", "Русский язык"],
    },
    {
        "faculty_name": "Университет",
        "direction_code": "ДИЗ",
        "direction_name": "Дизайн",
        "budget_places": 5,
        "paid_places": 10,
        "subjects": ["Рисунок", "Композиция", "Русский язык"],
    },
    {
        "faculty_name": "Университет",
        "direction_code": "ЭК",
        "direction_name": "Экономика",
        "budget_places": 8,
        "paid_places": 12,
        "subjects": ["Математика", "Обществознание", "Русский язык"],
    },
]
